// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivyaibcmlguavwnhqhji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2eWFpYmNtbGd1YXZ3bmhxaGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjU4NzUsImV4cCI6MjA2ODcwMTg3NX0.XmfdMDiRZzkGWyuuO6yVjEl6I2kVQuC7mxO94P2jKH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});